package com.rockbyte.vicu.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * DESIGN.md YAML token 块——Auralis 色板（唯一色值来源，仅 Light：
 * DESIGN.md 未定义暗色 token）。
 */
@Immutable
class AuralisColors(
    val surface: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val outline: Color,
    val outlineVariant: Color,
    val surfaceTint: Color,
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    val background: Color,
    val onBackground: Color,
    val surfaceVariant: Color,
)

val LightAuralisColors = AuralisColors(
    surface = Color(0xFFFDF8F8),
    surfaceDim = Color(0xFFDDD9D8),
    surfaceBright = Color(0xFFFDF8F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F3F2),
    surfaceContainer = Color(0xFFF1EDEC),
    surfaceContainerHigh = Color(0xFFEBE7E6),
    surfaceContainerHighest = Color(0xFFE5E2E1),
    onSurface = Color(0xFF1C1B1B),
    onSurfaceVariant = Color(0xFF444748),
    inverseSurface = Color(0xFF313030),
    inverseOnSurface = Color(0xFFF4F0EF),
    outline = Color(0xFF747878),
    outlineVariant = Color(0xFFC4C7C7),
    surfaceTint = Color(0xFF5F5E5E),
    primary = Color(0xFF000000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF1C1B1B),
    onPrimaryContainer = Color(0xFF858383),
    inversePrimary = Color(0xFFC8C6C5),
    secondary = Color(0xFF5E5E5E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE1DFDF),
    onSecondaryContainer = Color(0xFF626262),
    tertiary = Color(0xFF000000),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF1D1B1A),
    onTertiaryContainer = Color(0xFF868381),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    primaryFixed = Color(0xFFE5E2E1),
    primaryFixedDim = Color(0xFFC8C6C5),
    onPrimaryFixed = Color(0xFF1C1B1B),
    onPrimaryFixedVariant = Color(0xFF474646),
    secondaryFixed = Color(0xFFE4E2E2),
    secondaryFixedDim = Color(0xFFC7C6C6),
    onSecondaryFixed = Color(0xFF1B1C1C),
    onSecondaryFixedVariant = Color(0xFF464747),
    tertiaryFixed = Color(0xFFE6E1DF),
    tertiaryFixedDim = Color(0xFFCAC6C3),
    onTertiaryFixed = Color(0xFF1D1B1A),
    onTertiaryFixedVariant = Color(0xFF484645),
    background = Color(0xFFFDF8F8),
    onBackground = Color(0xFF1C1B1B),
    surfaceVariant = Color(0xFFE5E2E1),
)
